# Generated by Django 3.1.4 on 2020-12-08 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Drop_Off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_location', models.CharField(max_length=250)),
                ('drop_time', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('sin', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pick_Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_location', models.CharField(max_length=250)),
                ('pick_time', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Company',
            fields=[
                ('company_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('founded_date', models.DateField()),
                ('head_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Employee',
            fields=[
                ('e_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.employee')),
                ('license_grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('e_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.employee')),
                ('office_no', models.IntegerField(unique=True)),
                ('mgr_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Type',
            fields=[
                ('vin', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model_year', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('customers', models.ManyToManyField(through='api.Reservation', to='api.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('license_plate', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('total_no_seats', models.CharField(max_length=50)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rental_company')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='Transport_Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('customers_drop_off', models.ManyToManyField(related_name='do', through='api.Drop_Off', to='api.Customer')),
                ('customers_pick_up', models.ManyToManyField(related_name='pu', through='api.Pick_Up', to='api.Customer')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('workcode', models.CharField(max_length=50)),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle_type'),
        ),
        migrations.AddField(
            model_name='pick_up',
            name='transport_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transport_phase'),
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manager')),
            ],
        ),
        migrations.AddField(
            model_name='drop_off',
            name='transport_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transport_phase'),
        ),
        migrations.AddField(
            model_name='customer',
            name='transport_phases_drop_off',
            field=models.ManyToManyField(related_name='do', through='api.Drop_Off', to='api.Transport_Phase'),
        ),
        migrations.AddField(
            model_name='customer',
            name='transport_phases_pick_up',
            field=models.ManyToManyField(related_name='pu', through='api.Pick_Up', to='api.Transport_Phase'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_types',
            field=models.ManyToManyField(through='api.Reservation', to='api.Vehicle_Type'),
        ),
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transport_phase')),
            ],
        ),
        migrations.AddField(
            model_name='transport_phase',
            name='delivery_employees',
            field=models.ManyToManyField(through='api.Assigned', to='api.Delivery_Employee'),
        ),
        migrations.AddField(
            model_name='service',
            name='managers',
            field=models.ManyToManyField(through='api.Manages', to='api.Manager'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rate', models.FloatField()),
                ('total_price', models.FloatField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rental_company')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            options={
                'unique_together': {('customer_id', 'start_date', 'end_date', 'company_name')},
            },
        ),
        migrations.AddField(
            model_name='manager',
            name='services',
            field=models.ManyToManyField(through='api.Manages', to='api.Service'),
        ),
        migrations.AddField(
            model_name='delivery_employee',
            name='transport_phases',
            field=models.ManyToManyField(through='api.Assigned', to='api.Transport_Phase'),
        ),
        migrations.AddField(
            model_name='assigned',
            name='delivery_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.delivery_employee'),
        ),
        migrations.AlterUniqueTogether(
            name='transport_phase',
            unique_together={('date', 'time', 'vin')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('date', 'workcode', 'license_plate')},
        ),
    ]
