# Generated by Django 3.1.4 on 2020-12-07 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default='id', max_length=50, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('sin', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Company',
            fields=[
                ('company_name', models.CharField(default='id', max_length=50, primary_key=True, serialize=False)),
                ('founded_date', models.DateField()),
                ('head_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Type',
            fields=[
                ('vin', models.CharField(default='vin', max_length=50, primary_key=True, serialize=False)),
                ('model_year', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Employee',
            fields=[
                ('e_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.employee')),
                ('license_grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('e_id', models.OneToOneField(default='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.employee')),
                ('office_no', models.IntegerField()),
                ('mgr_start_date', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('license_plate', models.CharField(default='plate', max_length=250, primary_key=True, serialize=False)),
                ('total_no_seats', models.CharField(max_length=50)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rental_company')),
                ('vin', models.ForeignKey(default='vin', on_delete=django.db.models.deletion.CASCADE, to='api.vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='Transport_Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle_type')),
            ],
            options={
                'unique_together': {('date', 'time', 'vin')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('workcode', models.CharField(max_length=50)),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
            options={
                'unique_together': {('date', 'workcode', 'license_plate')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle_type')),
            ],
            options={
                'unique_together': {('customer_id', 'vin')},
            },
        ),
        migrations.CreateModel(
            name='Pick_Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_location', models.CharField(max_length=250)),
                ('pick_time', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu_date', to='api.transport_phase')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu_time', to='api.transport_phase')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu_vin', to='api.transport_phase')),
            ],
            options={
                'unique_together': {('date', 'time', 'vin', 'c_id')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rate', models.FloatField()),
                ('total_price', models.FloatField()),
                ('company_name', models.ForeignKey(default='name', on_delete=django.db.models.deletion.CASCADE, to='api.rental_company')),
                ('customer_id', models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            options={
                'unique_together': {('customer_id', 'start_date', 'end_date', 'company_name')},
            },
        ),
        migrations.CreateModel(
            name='Drop_Off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_location', models.CharField(max_length=250)),
                ('drop_time', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_date', to='api.transport_phase')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_time', to='api.transport_phase')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_vin', to='api.transport_phase')),
            ],
            options={
                'unique_together': {('date', 'time', 'vin', 'c_id')},
            },
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_date', to='api.service')),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('workcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_workcode', to='api.service')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manager')),
            ],
            options={
                'unique_together': {('m_id', 'license_plate', 'date', 'workcode')},
            },
        ),
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_date', to='api.transport_phase')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_time', to='api.transport_phase')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_vin', to='api.transport_phase')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.delivery_employee')),
            ],
            options={
                'unique_together': {('date', 'time', 'vin', 'd_id')},
            },
        ),
    ]
